### ISSUE TITLE
Stops with error: `/run/lock: mount point does not exist`

### ISSUE THREAD

**Issue by jpm-canonical** [ThinGuy/magenta-box#1]
I'm trying to set up this container using Docker Compose. When MAAS starts, it does an `apt-get update`, followed by enabling a systemd service. After this an error is printed and the execution halts.

```
maas-1      | Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
maas-1      | Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
maas-1      | Get:3 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [3527 kB]
maas-1      | Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
maas-1      | Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
maas-1      | Get:6 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
maas-1      | Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
maas-1      | Get:8 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [45.2 kB]
maas-1      | Get:9 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2560 kB]
maas-1      | Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1227 kB]
maas-1      | Get:11 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
maas-1      | Get:12 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
maas-1      | Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [53.3 kB]
maas-1      | Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [3663 kB]
maas-1      | Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1518 kB]
maas-1      | Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2859 kB]
maas-1      | Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [33.8 kB]
maas-1      | Get:18 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [81.4 kB]
maas-1      | Fetched 35.9 MB in 4s (8189 kB/s)
maas-1      | Reading package lists...
maas-1      | Created symlink /etc/systemd/system/default.target.wants/docker-exec.service → /etc/systemd/system/docker-exec.service.
maas-1      | mount: /run/lock: mount point does not exist.
```

Inside the container this directory does exist:
```
server:~/maas# docker compose exec maas bash
container:/# ls /run
credentials  dbus  lock  log  mount  nologin  sendsigs.omit.d  shm  snapd-snap.socket  snapd.socket  sudo  systemd  udev  user  utmp
container:/# ls /run/lock
subsys
```

My docker compose file looks like this:
```
services:
  maas:
    image: craigbender/cmaas:jammy-3.3
    privileged: true
    restart: unless-stopped
    environment:
      PGCON: "postgres://maas:maas@postgres:5432/maasdb"
      MAAS_DOMAIN: my.domain
      MAAS_CONTAINER_NAME: maas
      MAAS_PROFILE: admin
      MAAS_PASS: admin
      MAAS_EMAIL: maas-admin@my.domain
      MAAS_SSH_IMPORT_ID: lp:jpm
      MAAS_URL: "http://localhost:5240/MAAS"    
    ports:
      - 5240:5240
    command: |
      maas init region+rack --maas-url $${MAAS_URL} --database-uri $${PGCON} --force
      maas createadmin --username $${MAAS_PROFILE} --password $${MAAS_PASS} --email $${MAAS_EMAIL} --ssh-import $${MAAS_SSH_IMPORT_ID}
      maas login $${MAAS_PROFILE} http://localhost:5240/MAAS $$(maas apikey --username $${MAAS_PROFILE})
      bash

  postgres:
    image: postgres
    restart: always
    shm_size: 1gb
    environment:
      POSTGRES_USER: maas
      POSTGRES_PASSWORD: maas
      POSTGRES_DB: maasdb
```

---

Update:

If I run the container manually I see an additional error message:

`Failed to look up module alias 'autofs4': Function not implemented`

```
server:~/maas# docker compose run maas bash
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [3527 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]               
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2859 kB]       
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [53.3 kB]  
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [3663 kB]     
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1518 kB]     
Get:14 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [81.4 kB]       
Get:15 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [33.8 kB]    
Get:16 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [45.2 kB]  
Get:17 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1227 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2560 kB]
Fetched 35.9 MB in 5s (7303 kB/s)                          
Reading package lists... Done
Created symlink /etc/systemd/system/default.target.wants/docker-exec.service → /etc/systemd/system/docker-exec.service.
mount: /run/lock: mount point does not exist.
Failed to look up module alias 'autofs4': Function not implemented
systemd 249.11-0ubuntu3.9 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.
2025-01-15T09:30:41Z INFO Waiting for automatic snapd restart...
snapd 2.59.1 installed
WARNING: There is 1 new warning. See 'snap warnings'.
maas (3.5/stable) 3.5.3-16341-g.7adb035d6 from Canonical✓ installed
WARNING: There is 1 new warning. See 'snap warnings'.
Executing: 'bash '
container:/# 
```
